(ns <%= namespace %>
  "This file is generated by cljs-auto and should not be editted by hand.

  https://github.com/kwrooijen/cljs-auto
  "
  (:require
   <% (doseq [require requires] %><%= require %>
             <%) %>))

(def config
  <%= config %>)
